site_name: OSPSD Team 08 Chat Client

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api-reference.md
  - Implementation:
      - Discord Implementation: discord-implementation.md
  - Deployment:
      - Cloud Run: CLOUDRUN.md

theme:
  name: mkdocs