nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api-reference.md
  - Implementation:
      - Discord Implementation: discord-implementation.md
  - Deployment:
      - Cloud Run: CLOUDRUN.md
  - HW3:
      - Plan of Action: hw3-plan.md

theme:
  name: material