global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-discord-service'
    static_configs:
      # If running locally, use 'localhost:8000'
      # If running in Docker, use 'host.docker.internal:8000'
      - targets: ['app:8080']